# Generated by Django 3.0.7 on 2020-07-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todosy',
            name='wykonanie',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
